dist: trusty

env:
  global:
    secure: "ZniSfIKwXL7Lo1gPaopbDFkYls7GL4IQeIFmC+Azc73YIJC61UBQ/fNYnjEMR80E7407yp1+vYp/lu4h5aVmzn3X/FgPr+SwGYaBKv83uiM7xlO98313Z96zuGvN+RLEcZWjhGZri7mjS5Lg7O8CHiu/OnFKQbblbfYweNyaPoQKflygzfIR3d5I6Gjtf1UkzDnRIDFe4Ot7b+1xCJ6eF887D9Nr65N6c0BOMvcNMFY5UA0pH7XbZaYm7kO9J3kKy84Q+PsR8uClBVLVlkg0k+JEO03t8RkaFXNrS3OWYCkXaDYZ1qOAn38vY4jGSavkZUBzTIccWSM+h1B8SWXVH8KbKhKGPyxLgLgiItr4/lEOgz5ukNem9HQsFOMNoOus7IzFvr7RY3xY73wuizFs/qsZzwnlCyp05UXRs41EACdf+l4B3acfxlL5rgx/4XZil5TMYWCxSrrSnyIugNsi/xFAakpSIfEnnUcGE/85QrNxuhoq3NiihbhMLOUvs39IUqa41tRi+V5Gi9FZPeK6KM1I1HEKRCWD+qDbhKPjqAeeLLo8+5sNuXQQgkorhk3WErImgx75wIGlaMYC44RQYmQHiB3PNOLaKVMEqXCKsg7a9MEPTRMKiPhcbKSZUBYNFGGMuCixy+K4P+oY/FuF1wZq/cP0vYPQWkfBuXh4niw="

stages:
  - name: test
  - name: deploy-live
    if: branch = master AND type = push
  - name: deploy-staging
    if: branch = develop AND type = push

before_install:
- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in siwecosdeploy_rsa.enc -out siwecosdeploy_rsa -d
- chmod 600 siwecosdeploy_rsa

matrix:
  include:
    - language: node_js
      stage: test
      php: 7.2
      script:
        - npm install
        - npm run lint

    - language: node_js
      stage: deploy-staging
      node_js: lts/*
      script:
        - npm install
        - npm run build prod
        - rsync --progress -avz -e "ssh -i siwecosdeploy_rsa -o StrictHostKeyChecking=no -p 2244" ./dist/static/js/* ${SFTP_HOST}:/home/web4cshyx/html/staging.siwecos.de/spa/freescan

    - language: node_js
      stage: deploy-live
      node_js: lts/*
      script:
        - npm install
        - npm run build prod
        - rsync --progress -avz -e "ssh -i siwecosdeploy_rsa -o StrictHostKeyChecking=no -p 2244" ./dist/static/js/* ${SFTP_HOST}:/home/web4cshyx/html/siwecos.de/spa/freescan

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

sudo: required
